/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: examples/example.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "examples/example.pb-c.h"
void   something_with_uints__init
                     (SomethingWithUINTs         *message)
{
  static const SomethingWithUINTs init_value = SOMETHING_WITH_UINTS__INIT;
  *message = init_value;
}
size_t something_with_uints__get_packed_size
                     (const SomethingWithUINTs *message)
{
  assert(message->base.descriptor == &something_with_uints__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t something_with_uints__pack
                     (const SomethingWithUINTs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &something_with_uints__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t something_with_uints__pack_to_buffer
                     (const SomethingWithUINTs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &something_with_uints__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SomethingWithUINTs *
       something_with_uints__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SomethingWithUINTs *)
     protobuf_c_message_unpack (&something_with_uints__descriptor,
                                allocator, len, data);
}
void   something_with_uints__free_unpacked
                     (SomethingWithUINTs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &something_with_uints__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   something_more__init
                     (SomethingMore         *message)
{
  static const SomethingMore init_value = SOMETHING_MORE__INIT;
  *message = init_value;
}
size_t something_more__get_packed_size
                     (const SomethingMore *message)
{
  assert(message->base.descriptor == &something_more__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t something_more__pack
                     (const SomethingMore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &something_more__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t something_more__pack_to_buffer
                     (const SomethingMore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &something_more__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SomethingMore *
       something_more__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SomethingMore *)
     protobuf_c_message_unpack (&something_more__descriptor,
                                allocator, len, data);
}
void   something_more__free_unpacked
                     (SomethingMore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &something_more__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   even_more__init
                     (EvenMore         *message)
{
  static const EvenMore init_value = EVEN_MORE__INIT;
  *message = init_value;
}
size_t even_more__get_packed_size
                     (const EvenMore *message)
{
  assert(message->base.descriptor == &even_more__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t even_more__pack
                     (const EvenMore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &even_more__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t even_more__pack_to_buffer
                     (const EvenMore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &even_more__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EvenMore *
       even_more__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EvenMore *)
     protobuf_c_message_unpack (&even_more__descriptor,
                                allocator, len, data);
}
void   even_more__free_unpacked
                     (EvenMore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &even_more__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor something_with_uints__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SomethingWithUINTs, has_id),
    offsetof(SomethingWithUINTs, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_address",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SomethingWithUINTs, has_ip_address),
    offsetof(SomethingWithUINTs, ip_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port_num",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SomethingWithUINTs, has_port_num),
    offsetof(SomethingWithUINTs, port_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned something_with_uints__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = ip_address */
  2,   /* field[2] = port_num */
};
static const ProtobufCIntRange something_with_uints__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor something_with_uints__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SomethingWithUINTs",
  "SomethingWithUINTs",
  "SomethingWithUINTs",
  "",
  sizeof(SomethingWithUINTs),
  3,
  something_with_uints__field_descriptors,
  something_with_uints__field_indices_by_name,
  1,  something_with_uints__number_ranges,
  (ProtobufCMessageInit) something_with_uints__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue something_more__errors__enum_values_by_number[5] =
{
  { "SUCCESS", "SOMETHING_MORE__ERRORS__SUCCESS", 200 },
  { "ERROR_BAD_REQUEST", "SOMETHING_MORE__ERRORS__ERROR_BAD_REQUEST", 400 },
  { "ERROR_NOT_FOUND", "SOMETHING_MORE__ERRORS__ERROR_NOT_FOUND", 404 },
  { "ERROR_SERVER_ERROR", "SOMETHING_MORE__ERRORS__ERROR_SERVER_ERROR", 500 },
  { "ERROR_SERVICE_UNAVAILABLE", "SOMETHING_MORE__ERRORS__ERROR_SERVICE_UNAVAILABLE", 503 },
};
static const ProtobufCIntRange something_more__errors__value_ranges[] = {
{200, 0},{400, 1},{404, 2},{500, 3},{503, 4},{0, 5}
};
static const ProtobufCEnumValueIndex something_more__errors__enum_values_by_name[5] =
{
  { "ERROR_BAD_REQUEST", 1 },
  { "ERROR_NOT_FOUND", 2 },
  { "ERROR_SERVER_ERROR", 3 },
  { "ERROR_SERVICE_UNAVAILABLE", 4 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor something_more__errors__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SomethingMore.Errors",
  "Errors",
  "SomethingMore__Errors",
  "",
  5,
  something_more__errors__enum_values_by_number,
  5,
  something_more__errors__enum_values_by_name,
  5,
  something_more__errors__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor something_more__field_descriptors[2] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SomethingMore, has_error_code),
    offsetof(SomethingMore, error_code),
    &something_more__errors__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uints",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SomethingMore, uints),
    &something_with_uints__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned something_more__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
  1,   /* field[1] = uints */
};
static const ProtobufCIntRange something_more__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor something_more__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SomethingMore",
  "SomethingMore",
  "SomethingMore",
  "",
  sizeof(SomethingMore),
  2,
  something_more__field_descriptors,
  something_more__field_indices_by_name,
  1,  something_more__number_ranges,
  (ProtobufCMessageInit) something_more__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue even_more__some_enum__enum_values_by_number[2] =
{
  { "FIRST", "EVEN_MORE__SOME_ENUM__FIRST", 254 },
  { "SECOND", "EVEN_MORE__SOME_ENUM__SECOND", 255 },
};
static const ProtobufCIntRange even_more__some_enum__value_ranges[] = {
{254, 0},{0, 2}
};
static const ProtobufCEnumValueIndex even_more__some_enum__enum_values_by_name[2] =
{
  { "FIRST", 0 },
  { "SECOND", 1 },
};
const ProtobufCEnumDescriptor even_more__some_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EvenMore.SomeEnum",
  "SomeEnum",
  "EvenMore__SomeEnum",
  "",
  2,
  even_more__some_enum__enum_values_by_number,
  2,
  even_more__some_enum__enum_values_by_name,
  1,
  even_more__some_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor even_more__field_descriptors[5] =
{
  {
    "enum_value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EvenMore, enum_value),
    &even_more__some_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uints",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EvenMore, n_uints),
    offsetof(EvenMore, uints),
    &something_with_uints__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EvenMore, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EvenMore, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EvenMore, s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned even_more__field_indices_by_name[] = {
  0,   /* field[0] = enum_value */
  2,   /* field[2] = name */
  4,   /* field[4] = s */
  1,   /* field[1] = uints */
  3,   /* field[3] = value */
};
static const ProtobufCIntRange even_more__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor even_more__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EvenMore",
  "EvenMore",
  "EvenMore",
  "",
  sizeof(EvenMore),
  5,
  even_more__field_descriptors,
  even_more__field_indices_by_name,
  1,  even_more__number_ranges,
  (ProtobufCMessageInit) even_more__init,
  NULL,NULL,NULL    /* reserved[123] */
};
